menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- 'MATH0200: Multivariable Calculus (Physics/Engineering)'
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/ldswko'}
- {icon: 'instagram', link: 'https://instagram.com/ldswko'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/ldswko'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
